# Generated by Django 4.0.5 on 2023-01-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairitems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
